name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Create BCC Package
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
        if: always()
